name 'xerireu/infiniband'
version '0.1.0'
source 'git://github.com/xerireu/puppet-module-infiniband.git'
author 'xerireu'
license 'Apache License, Version 2.0'
summary 'put a summary here'
description 'put a description here'
project_page 'https://github.com/xerireu/puppet-module-infiniband'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
