name 'xerireu/infiniband'
version '0.3.3'
source 'git://github.com/xerireu/puppet-module-infiniband.git'
author 'xerireu'
license 'Apache License, Version 2.0'
summary 'This modules manages hosts in a infiniband network with both IPoIB Xsigo virtual ethernet interfaces'
description 'This modules manages hosts in a infiniband network with both IPoIB Xsigo virtual ethernet interfaces'
project_page 'https://github.com/xerireu/puppet-module-infiniband'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
